# Generated by Django 5.1.4 on 2025-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EC', 'Economy'), ('ST', 'Standard'), ('LX', 'Luxe'), ('AL', 'All Rooms')], default='AL', max_length=100)),
                ('members', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('SB', 'Single bed'), ('DB', 'Double Bed')], default='SB', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
