# Generated by Django 5.1.6 on 2025-02-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('triple', 'Triple Bed')], max_length=50),
        ),
    ]
