# Generated by Django 5.1.6 on 2025-02-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(choices=[('single', 'Single Bedroom'), ('double', 'Double Bedroom'), ('triple', 'Triple Bedroom')], max_length=50),
        ),
    ]
