# Generated by Django 5.1.6 on 2025-02-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.roomcategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(choices=[('S', 'Single Bedroom'), ('D', 'Double Bedroom'), ('T', 'Triple Bedroom')], max_length=1),
        ),
    ]
