# Generated by Django 5.1.6 on 2025-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_coupon_reservation_address_reservation_adhar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
