# Generated by Django 5.1.6 on 2025-03-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_reservation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('pay_on_arrival', 'Pay on Arrival'), ('upi', 'UPI'), ('cards', 'Cards')], default='pay_on_arrival', max_length=20),
        ),
    ]
