# Generated by Django 5.1.6 on 2025-03-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('rooms', '0005_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
